import { PriceReport, LanguageCopy, SupportedLanguage } from "./types";

export const INITIAL_REPORTS: PriceReport[] = [
  {
    id: "rep-1",
    productName: "Crate of Eggs",
    category: "food",
    unit: "Crate",
    price: 4200,
    prevPrice: 4000,
    changePercent: 5,
    trend: "up",
    marketName: "Mile 12 Market",
    state: "Lagos",
    verified: true,
    contributor: "Chinedu K.",
    dateObserved: "2026-06-05",
    comments: "Bargained extensively. Best quality eggs are in the middle section of the market.",
    icon: "🥚",
    upvotes: 48,
    downvotes: 2
  },
  {
    id: "rep-2",
    productName: "Petrol (PMS)",
    category: "fuel",
    unit: "Per Litre",
    price: 680,
    prevPrice: 680,
    changePercent: 0,
    trend: "stable",
    marketName: "TotalEnergies",
    state: "Abuja",
    verified: true,
    contributor: "Yusuf M.",
    dateObserved: "2026-06-05",
    comments: "Normal pump pricing. Safe lines, no black market price yet.",
    icon: "⛽",
    upvotes: 112,
    downvotes: 4
  },
  {
    id: "rep-3",
    productName: "Dangote Cement",
    category: "construction",
    unit: "50kg Bag",
    price: 10500,
    prevPrice: 10700,
    changePercent: 2,
    trend: "down",
    marketName: "Bodija Market",
    state: "Ibadan, Oyo",
    verified: false,
    contributor: "Olukayode O.",
    dateObserved: "2026-06-04",
    comments: "Prices dropping slightly due to off-season discount from wholesalers.",
    icon: "🧱",
    upvotes: 28,
    downvotes: 1
  },
  {
    id: "rep-4",
    productName: "Garri (White)",
    category: "food",
    unit: "Mudu",
    price: 750,
    prevPrice: 765,
    changePercent: 2,
    trend: "down",
    marketName: "Bodija Market",
    state: "Ibadan, Oyo",
    verified: false,
    contributor: "Aishat B.",
    dateObserved: "2026-06-05",
    comments: "Available in abundance. White garri from Ogbomoso is very dry and sweet.",
    icon: "🥣",
    upvotes: 45,
    downvotes: 2
  },
  {
    id: "rep-5",
    productName: "Tomatoes (Big Basket)",
    category: "food",
    unit: "Large Basket",
    price: 32000,
    prevPrice: 28500,
    changePercent: 12,
    trend: "up",
    marketName: "Mile 12 Market",
    state: "Lagos",
    verified: true,
    contributor: "Mama Tunde",
    dateObserved: "2026-06-05",
    comments: "Heavy delays in supply trucks from the North. Prices might go higher by weekend.",
    icon: "🍅",
    upvotes: 82,
    downvotes: 5
  },
  {
    id: "rep-6",
    productName: "Local Rice (50kg)",
    category: "food",
    unit: "50kg Bag",
    price: 48000,
    prevPrice: 45000,
    changePercent: 6,
    trend: "up",
    marketName: "Singer Market",
    state: "Kano",
    verified: true,
    contributor: "Ibrahim K.",
    dateObserved: "2026-06-03",
    comments: "Clean stone-free destoned local rice. Premium grade.",
    icon: "🌾",
    upvotes: 64,
    downvotes: 3
  }
];

export const LANGUAGE_TRANSLATIONS: Record<SupportedLanguage, LanguageCopy> = {
  en: {
    heroTitle: "Find the real price. From real Nigerians.",
    heroSub: "Join 50,000+ contributors tracking daily market costs across 36 states. No more 'market shock' at the counter.",
    searchPlaceholder: "Search for Rice, Fuel, Cement...",
    popularLabel: "Popular:",
    reportsTitle: "Recently Reported Prices",
    reportsSub: "Live updates from markets across the country.",
    viewAll: "View all reports",
    emptyTitle: "No price found for '{query}' yet.",
    emptySub: "Prices at the local market move fast! You can help the community by sharing what you've seen today.",
    beFirstBtn: "Be the first to add it",
    browseBtn: "Browse Categories",
    boughtTitle: "Bought something today?",
    boughtSub: "Your report helps thousands of Nigerians make better financial decisions. Spend 30 seconds to help the community.",
    submitBtn: "Submit a Price Report"
  },
  pidgin: {
    heroTitle: "Find the real price. From real Nigerians.",
    heroSub: "Join over 50,000 people dey track market price across 36 states every day. Market shock no go catch you again.",
    searchPlaceholder: "Search for Rice, Fuel, Cement...",
    popularLabel: "Popular:",
    reportsTitle: "Prices Wey People Just Report",
    reportsSub: "Live updates from different markets for Nigeria.",
    viewAll: "See all reports",
    emptyTitle: "We never find the price for '{query}' yet.",
    emptySub: "Market price dey run fast fast! Help your people tell us wetin you buy or see for market today.",
    beFirstBtn: "Be the first person to add am",
    browseBtn: "Look other things",
    boughtTitle: "You buy something today?",
    boughtSub: "Wetin you post go help plenty Nigerians save money. Just take 30 seconds help the community.",
    submitBtn: "Post Price Report"
  },
  yo: {
    heroTitle: "Waye lori idi gidi. Lati enu awon omo Naijiria gangan.",
    heroSub: "Darapọ mọ awọn oluranlọwọ ti o to 50,000+ ti n tọpa awọn idiyele lojoojumọ kọja awọn ipinlẹ 36.",
    searchPlaceholder: "Wa iresi, epo, simenti tabi nkan miiran...",
    popularLabel: "Gbajumo:",
    reportsTitle: "Awọn Iye Ti A Sọ Laipẹ Yi",
    reportsSub: "Awọn imudojuiwọn laaye lati awọn ọja kaakiri orilẹ-ede.",
    viewAll: "Wo gbogbo iroyin",
    emptyTitle: "A ko tii ri idiyele fun '{query}'.",
    emptySub: "Awọn idiyele ọja n yipada ni kiakia! O le ṣe iranlọwọ fun agbegbe nipa pinpin ohun ti o rii loni.",
    beFirstBtn: "Jẹ ẹni akọkọ lati tẹ ẹ sọ",
    browseBtn: "Wo awon eka miran",
    boughtTitle: "Ṣe o ra nkan loni?",
    boughtSub: "Iroyin rẹ n ṣe iranlọwọ fun ẹgbẹẹgbẹrun eniyan lati ṣe ipinnu to dara. Lo iṣẹju-aaya 30 lati ran agbegbe lọwọ.",
    submitBtn: "Fi Iye Nkan Riranṣẹ"
  },
  ig: {
    heroTitle: "Chọta ezigbo ọnụahịa. Site n'ọnụ ndị Naijiria gbara mbọ.",
    heroSub: "Soro ihe karịrị mmadụ 50,000 na-enyocha ọnụahịa ahịa kwa ụbọchị gafee steeti 36.",
    searchPlaceholder: "Chọọ osikapa, mmanụ ụgbọala, simenti...",
    popularLabel: "Ihe Ndị Na-ewu Ewu:",
    reportsTitle: "Ọnụahịa Atụnyere Na Nso Nso A",
    reportsSub: "Ihe emelitere ozugbo site n'ahịa dị iche iche na mba anyị.",
    viewAll: "Lelee akụkọ niile",
    emptyTitle: "Anyị ahụbeghị ọnụahịa maka '{query}' ugbu a.",
    emptySub: "Ọnụahịa ahịa na-agbanwe ngwa ngwa! I nwere ike inyere ndị obodo ahụ aka site n'ịkọrọ anyị ihe ị hụrụ taa.",
    beFirstBtn: "Burụ onye mbụ tinye ya",
    browseBtn: "Chọgharịa udi ndị ọzọ",
    boughtTitle: "Ị zụrụ ihe taa?",
    boughtSub: "Ihe ị na-ede ga-enyere ọtụtụ puku ndị Naijiria aka ịchekwa ego. Were sekọnd 30 nyere obodo aka.",
    submitBtn: "Zipụ Ọnụahịa Ahụ"
  },
  ha: {
    heroTitle: "Nemi ainihin farashi. Daga bakin 'yan Najeriya na gari.",
    heroSub: "Kasance tare da masu ba da gudummawa 50,000+ da ke bin diddigin farashin kasuwanni a kullum a sassan jihohi 36.",
    searchPlaceholder: "Nemi shinkafa, mai, siminti ko wani abu na daban...",
    popularLabel: "Mafi Shahara:",
    reportsTitle: "Farashin Da Aka Ruwaito Kwanan Nan",
    reportsSub: "Rahotanni kai tsaye daga kasuwanni daban daban na kasar nan.",
    viewAll: "Duba dukkan rahotanni",
    emptyTitle: "Ba a sami farashin '{query}' ba tukunna.",
    emptySub: "Farashin kasuwanni na tashi cikin sauri! Kuna iya taimaka wa al'umma ta hanyar raba abin da kuka gani a yau.",
    beFirstBtn: "Zama na farko wajen ƙarawa",
    browseBtn: "Duba sauran rukunoni",
    boughtTitle: "Ka sayi wani abu yau?",
    boughtSub: "Rahotonku zai taimaka wa dubban abokan ku yanke shawara mai kyau akan kudi. Sanya sakan 30 don taimaka musu.",
    submitBtn: "Aika Rahoton Farashi"
  }
};
